### ISSUE TITLE
安装成功了，但是输入账号密码后报错

### ISSUE THREAD

**Issue by zhxwayne** [DyingLight12/Android_Learning#19]
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 21, in user_flag
    cookies = dingding.dd_login_status(uname)
  File "/root/pdlearn/dingding.py", line 23, in dd_login_status
    driver_login = mydriver.Mydriver(noimg=False)
  File "/root/pdlearn/mydriver.py", line 47, in __init__
    self.driver = self.webdriver.Chrome(chrome_options=self.options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by zhxwayne** [comment]
重装以后，又出现如下报错，怎么回事，不稳定？

Traceback (most recent call last):
  File "pandalearning.py", line 6, in <module>
    from pdlearn import dingding
  File "/root/pdlearn/dingding.py", line 2, in <module>
    from pdlearn import mydriver                             File "/root/pdlearn/mydriver.py", line 1, in <module>
    ﻿from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by zhxwayne** [comment]
重装第2次后，报错如下：
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 21, in user_flag               cookies = dingding.dd_login_status(uname)
  File "/root/pdlearn/dingding.py", line 24, in dd_login_status                                                           login_status = driver_login.dd_login(dname, pwd)
  File "/root/pdlearn/mydriver.py", line 95, in dd_login       self.driver.find_elements_by_id("mobilePlaceholder")[0].click()
IndexError: list index out of range

**Comment by oooasis** [comment]
解决了吗

**Comment by wangdetao8341** [comment]
你这解决了吗
