### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by a2008zhang** [DyingLight12/Android_Learning#5]
老哥登陆上时候输入手机号和密码出现提示，初始化失败，怎么回事
========
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 18, in user_flag
    driver_login = mydriver.Mydriver(nohead=False)
  File "/root/pdlearn/mydriver.py", line 47, in __init__
    s

![1e9a126d7fb87a7970d719f43f86825](https://user-images.githubusercontent.com/49052256/57750552-4bb9d800-7715-11e9-95e7-851d255da185.png)

**Comment by rangeyo** [comment]
同样的问题

**Comment by klcb2010** [comment]
重装系统看看 需要全程梯子

**Comment by a2008zhang** [comment]
重新装一下就好了，我事先给termux未知应用安装权限和读取写入内存权限，然后按照步骤重新按照就好了，中途不要退出。
